version: '3'
volumes:
    postgres_vol:
services:
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - "./database/init:/docker-entrypoint-initdb.d"
            - "postgres_vol:/var/lib/postgresql/data"
    auth-service-migrate:
        image: boxfuse/flyway
        command: -url=jdbc:postgresql://database:5432/studit_auth -user=postgres -password=postgres migrate
        volumes:
            - "./database/migrations/auth-service:/flyway/sql"
        links:
            - "postgres:database"
        restart: on-failure
    auth-service:
        build: "./backend/src/auth-service/"
        links:
            - "postgres:database"
            - "data-service:data-service"
        restart: always
    data-service-migrate:
        image: boxfuse/flyway
        command: -url=jdbc:postgresql://database:5432/studit_data -user=postgres -password=postgres migrate
        volumes:
            - "./database/migrations/data-service:/flyway/sql"
        links:
            - "postgres:database"
        restart: on-failure
    data-service:
        build: "./backend/src/data-service/"
        links:
            - "postgres:database"
        restart: always
    file-service-migrate:
        image: boxfuse/flyway
        command: -url=jdbc:postgresql://database:5432/studit_file -user=postgres -password=postgres migrate
        volumes:
            - "./database/migrations/file-service:/flyway/sql"
        links:
            - "postgres:database"
        restart: on-failure
    file-service:
        build: "./backend/src/file-service/"
        links:
            - "postgres:database"
        restart: always
    main-service:
        build: "./backend/src/main-service/"
        ports:
            - "8080:8080"
        links:
            - "file-service:file-service"
            - "data-service:data-service"
            - "auth-service:auth-service"
        restart: always
    frontend:
        build: "./frontend"
        ports:
            - "80:80"
        restart: always