package controllers

const (
	HTTP_OK = 200
	HTTP_CREATED = 201
	HTTP_BAD_REQUEST = 400
	HTTP_UNAUTHORIZED = 401
	HTTP_FORBIDDEN = 403
	HTTP_INTERNAL_SERVER_ERROR = 500
)

const (
	HTTP_OK_STR = "OK"
	HTTP_CREATED_STR = "Created"
	HTTP_BAD_REQUEST_STR = "Bad Request"
	HTTP_UNAUTHORIZED_STR = "Unauthorized"
	HTTP_FORBIDDEN_STR = "Forbidden"
	HTTP_INTERNAL_SERVER_ERROR_STR = "Internal Server Error"
)
